name: lfw_mobile
description: Lagos Fashion Week Mobile App.
version: 0.0.1+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-UI-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-UI-Display-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SF-UI-Display-Bold.ttf
          weight: 900
