name: glam
description: Lagos Fashion Week Mobile App.
version: 0.0.1+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.0.4
  photo_view: ^0.0.2
  flutter_spinkit: ^2.0.0
  url_launcher: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: MkIcons
      fonts:
        - asset: assets/fonts/MkIcons.ttf

    - family: Source Code Pro
      fonts:
        - asset: assets/fonts/SourceCodePro-Light.ttf
          weight: 200
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceCodePro-Medium.ttf
          weight: 600
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 900
